before:
    hooks:
        - go mod tidy
        - go generate ./...
brews:
    - description: go-go-labs contains experimental go go tools
      homepage: https://github.com/go-go-golems/go-go-labs
      name: go-go-labs
      repository:
        name: homebrew-go-go-go
        owner: go-go-golems
        token: '{{ .Env.TAP_GITHUB_TOKEN }}'
builds:
    - binary: mastoid
      env:
        - CGO_ENABLED=0
      goos:
        - linux
        - darwin
      main: ./cmd/mastoid
changelog:
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - null
    sort: asc
checksum:
    name_template: checksums.txt
furies:
    - account: go-go-golems
      ids:
        - packages
nfpms:
    - deb:
        lintian_overrides:
            - statically-linked-binary
            - changelog-file-missing-in-native-package
      description: go-go-labs contains experimental go go tools
      formats:
        - deb
        - rpm
      homepage: https://github.com/go-go-golems/
      id: packages
      license: MIT
      maintainer: Manuel Odendahl <wesen@ruinwesen.com>
      priority: extra
      release: 1
      section: default
      vendor: GO GO GOLEMS
project_name: go-go-labs
publishers:
    - cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/go-go-golems/
      dir: '{{ dir .ArtifactPath }}'
      ids:
        - packages
      name: fury.io
signs:
    - args:
        - --batch
        - -u
        - '{{ .Env.GPG_FINGERPRINT }}'
        - --output
        - ${signature}
        - --detach-sign
        - ${artifact}
      artifacts: checksum
snapshot:
    name_template: '{{ incpatch .Version }}-next'
version: 2
