// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: meshtastic/xmodem.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XModem_Control int32

const (
	XModem_NUL   XModem_Control = 0
	XModem_SOH   XModem_Control = 1
	XModem_STX   XModem_Control = 2
	XModem_EOT   XModem_Control = 4
	XModem_ACK   XModem_Control = 6
	XModem_NAK   XModem_Control = 21
	XModem_CAN   XModem_Control = 24
	XModem_CTRLZ XModem_Control = 26
)

// Enum value maps for XModem_Control.
var (
	XModem_Control_name = map[int32]string{
		0:  "NUL",
		1:  "SOH",
		2:  "STX",
		4:  "EOT",
		6:  "ACK",
		21: "NAK",
		24: "CAN",
		26: "CTRLZ",
	}
	XModem_Control_value = map[string]int32{
		"NUL":   0,
		"SOH":   1,
		"STX":   2,
		"EOT":   4,
		"ACK":   6,
		"NAK":   21,
		"CAN":   24,
		"CTRLZ": 26,
	}
)

func (x XModem_Control) Enum() *XModem_Control {
	p := new(XModem_Control)
	*p = x
	return p
}

func (x XModem_Control) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (XModem_Control) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_xmodem_proto_enumTypes[0].Descriptor()
}

func (XModem_Control) Type() protoreflect.EnumType {
	return &file_meshtastic_xmodem_proto_enumTypes[0]
}

func (x XModem_Control) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use XModem_Control.Descriptor instead.
func (XModem_Control) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_xmodem_proto_rawDescGZIP(), []int{0, 0}
}

type XModem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Control       XModem_Control         `protobuf:"varint,1,opt,name=control,proto3,enum=meshtastic.XModem_Control" json:"control,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Crc16         uint32                 `protobuf:"varint,3,opt,name=crc16,proto3" json:"crc16,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,4,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XModem) Reset() {
	*x = XModem{}
	mi := &file_meshtastic_xmodem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XModem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XModem) ProtoMessage() {}

func (x *XModem) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_xmodem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XModem.ProtoReflect.Descriptor instead.
func (*XModem) Descriptor() ([]byte, []int) {
	return file_meshtastic_xmodem_proto_rawDescGZIP(), []int{0}
}

func (x *XModem) GetControl() XModem_Control {
	if x != nil {
		return x.Control
	}
	return XModem_NUL
}

func (x *XModem) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *XModem) GetCrc16() uint32 {
	if x != nil {
		return x.Crc16
	}
	return 0
}

func (x *XModem) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

var File_meshtastic_xmodem_proto protoreflect.FileDescriptor

const file_meshtastic_xmodem_proto_rawDesc = "" +
	"\n" +
	"\x17meshtastic/xmodem.proto\x12\n" +
	"meshtastic\"\xd3\x01\n" +
	"\x06XModem\x124\n" +
	"\acontrol\x18\x01 \x01(\x0e2\x1a.meshtastic.XModem.ControlR\acontrol\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x12\x14\n" +
	"\x05crc16\x18\x03 \x01(\rR\x05crc16\x12\x16\n" +
	"\x06buffer\x18\x04 \x01(\fR\x06buffer\"S\n" +
	"\aControl\x12\a\n" +
	"\x03NUL\x10\x00\x12\a\n" +
	"\x03SOH\x10\x01\x12\a\n" +
	"\x03STX\x10\x02\x12\a\n" +
	"\x03EOT\x10\x04\x12\a\n" +
	"\x03ACK\x10\x06\x12\a\n" +
	"\x03NAK\x10\x15\x12\a\n" +
	"\x03CAN\x10\x18\x12\t\n" +
	"\x05CTRLZ\x10\x1aBa\n" +
	"\x13com.geeksville.meshB\fXmodemProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00b\x06proto3"

var (
	file_meshtastic_xmodem_proto_rawDescOnce sync.Once
	file_meshtastic_xmodem_proto_rawDescData []byte
)

func file_meshtastic_xmodem_proto_rawDescGZIP() []byte {
	file_meshtastic_xmodem_proto_rawDescOnce.Do(func() {
		file_meshtastic_xmodem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtastic_xmodem_proto_rawDesc), len(file_meshtastic_xmodem_proto_rawDesc)))
	})
	return file_meshtastic_xmodem_proto_rawDescData
}

var file_meshtastic_xmodem_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meshtastic_xmodem_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meshtastic_xmodem_proto_goTypes = []any{
	(XModem_Control)(0), // 0: meshtastic.XModem.Control
	(*XModem)(nil),      // 1: meshtastic.XModem
}
var file_meshtastic_xmodem_proto_depIdxs = []int32{
	0, // 0: meshtastic.XModem.control:type_name -> meshtastic.XModem.Control
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meshtastic_xmodem_proto_init() }
func file_meshtastic_xmodem_proto_init() {
	if File_meshtastic_xmodem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtastic_xmodem_proto_rawDesc), len(file_meshtastic_xmodem_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtastic_xmodem_proto_goTypes,
		DependencyIndexes: file_meshtastic_xmodem_proto_depIdxs,
		EnumInfos:         file_meshtastic_xmodem_proto_enumTypes,
		MessageInfos:      file_meshtastic_xmodem_proto_msgTypes,
	}.Build()
	File_meshtastic_xmodem_proto = out.File
	file_meshtastic_xmodem_proto_goTypes = nil
	file_meshtastic_xmodem_proto_depIdxs = nil
}
